-- DDL

CREATE USER JAKARTA_DATA_USER IDENTIFIED BY <JAKARTA_DATA_USER_PASSWORD> QUOTA UNLIMITED ON USERS; 
GRANT DB_DEVELOPER_ROLE TO JAKARTA_DATA_USER;  
GRANT CREATE SESSION TO JAKARTA_DATA_USER;  
GRANT SELECT ANY TABLE ON SCHEMA JAKARTA_DATA_USER TO JAKARTA_DATA_USER;  
ALTER SESSION SET CURRENT_SCHEMA = JAKARTA_DATA_USER;  

-- DML

DESCRIBE JAKARTA_DATA_USER.MARTIALART;

SELECT COUNT(*) FROM JAKARTA_DATA_USER.MARTIALART;

SELECT * FROM JAKARTA_DATA_USER.MARTIALART;

